export const CHANGE_ACTIVE_SCREEN = 'CHANGE_ACTIVE_SCREEN';
export const INITIALIZE_SCREENS = 'INITIALIZE_SCREENS';
export const MOVE_TO_NEXT_SCREEN = 'MOVE_TO_NEXT_SCREEN';
export const SWITCH_THEME = 'SWITCH_THEME';
